AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Lambda application that calls the Lambda API.
Resources:
  bucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
  function:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: build/distributions/fhir-java-lambda.zip
      Handler: example.HandlerS3
      Runtime: java11
      Description: Java function
      MemorySize: 512
      Timeout: 10
      # Function's execution role
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSLambdaReadOnlyAccess
        - AWSXrayWriteOnlyAccess
        - AWSLambdaVPCAccessExecutionRole
        - AmazonS3FullAccess
      Tracing: Active
      Layers:
        - !Ref libs
      Events:
        s3Notification:
          Type: S3
          Properties:
            Bucket: !Ref bucket
            Events: s3:ObjectCreated:*
            Filter:
              S3Key:
                Rules:
                - Name: prefix
                  Value: inbound/
      Environment:
        Variables:
          ENV_USERNAME: ""
          ENV_PASSWORD: ""
          ENV_ACCESS_KEY: ""
          ENV_SECRET_KEY: ""
          ENV_USER_POOL: ""
          ENV_CLIENT_ID: ""
  libs:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: fhir-java-lambda-lib
      Description: Dependencies for the fhir-java-lambda sample app.
      ContentUri: build/fhir-java-lambda-lib.zip
      CompatibleRuntimes:
        - java11